### PR TITLE
Update classifier

### PR DESCRIPTION
**Pull request by sunpoet**
v1.0.0 removes Python 2.7 and all 3.x versions below 3.6.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much! :)

**Comment by chrissimpkins** [comment]
I added a few other changes to the setup.py file in https://github.com/source-foundry/font-v/commit/5f8004493ae9888ded15cd07b73411699c45ecd3 and will push a new release.  Thanks for your changes here!

**Comment by chrissimpkins** [comment]
https://pypi.org/project/font-v/1.0.2/

**Comment by sunpoet** [comment]
Thanks!

**Pull request merged**
